# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uas.py'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(827, 632)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setGeometry(QtCore.QRect(10, 30, 541, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 47, 13))
        self.label.setObjectName("label")
        self.crawl = QtWidgets.QPushButton(self.centralwidget)
        self.crawl.setEnabled(False)
        self.crawl.setGeometry(QtCore.QRect(650, 30, 75, 31))
        self.crawl.setObjectName("crawl")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 340, 111, 16))
        self.label_3.setObjectName("label_3")
        self.summ = QtWidgets.QPushButton(self.centralwidget)
        self.summ.setEnabled(False)
        self.summ.setGeometry(QtCore.QRect(730, 30, 75, 31))
        self.summ.setObjectName("summ")
        self.openfile = QtWidgets.QPushButton(self.centralwidget)
        self.openfile.setEnabled(False)
        self.openfile.setGeometry(QtCore.QRect(570, 30, 75, 31))
        self.openfile.setObjectName("openfile")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setEnabled(False)
        self.textEdit.setGeometry(QtCore.QRect(10, 90, 801, 251))
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setEnabled(False)
        self.textEdit_2.setGeometry(QtCore.QRect(10, 360, 801, 231))
        self.textEdit_2.setObjectName("textEdit_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 827, 21))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuText_sum = QtWidgets.QMenu(self.menubar)
        self.menuText_sum.setObjectName("menuText_sum")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.file = QtWidgets.QAction(MainWindow)
        self.file.setEnabled(True)
        self.file.setObjectName("file")
        self.webb = QtWidgets.QAction(MainWindow)
        self.webb.setObjectName("webb")
        self.about = QtWidgets.QAction(MainWindow)
        self.about.setObjectName("about")
        self.actionAbout_2 = QtWidgets.QAction(MainWindow)
        self.actionAbout_2.setObjectName("actionAbout_2")
        self.actionMengetik = QtWidgets.QAction(MainWindow)
        self.actionMengetik.setObjectName("actionMengetik")
        self.menuHelp.addAction(self.about)
        self.menuHelp.addAction(self.actionAbout_2)
        self.menuText_sum.addAction(self.file)
        self.menuText_sum.addAction(self.webb)
        self.menuText_sum.addAction(self.actionMengetik)
        self.menubar.addAction(self.menuText_sum.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "UAS WEB MINNING 17062"))
        self.label.setText(_translate("MainWindow", "URL ="))
        self.crawl.setText(_translate("MainWindow", "Crawl"))
        self.label_2.setText(_translate("MainWindow", "Text ="))
        self.label_3.setText(_translate("MainWindow", "Text Summarization ="))
        self.summ.setText(_translate("MainWindow", "Ringkaskan"))
        self.openfile.setText(_translate("MainWindow", "Open File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuText_sum.setTitle(_translate("MainWindow", "Text sum"))
        self.file.setText(_translate("MainWindow", "From File"))
        self.webb.setText(_translate("MainWindow", "From Website"))
        self.about.setText(_translate("MainWindow", "Help"))
        self.actionAbout_2.setText(_translate("MainWindow", "About"))
        self.actionMengetik.setText(_translate("MainWindow", "Mengetik"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
